import type { Dict } from './strings.ko';

/**
 * English strings. Typed as `Dict` (the Korean file is the source of truth),
 * so a missing key is a compile error rather than a blank label at runtime.
 */
export const EN: Dict = {
  common: {
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    add: 'Add',
    close: 'Close',
    back: 'Back',
    done: 'Done',
    edit: 'Edit',
    retry: 'Try again',
    home: 'Home',
    loading: 'Loading…',
    empty: 'Empty',
    tryAgain: 'Please try again.',
    notFound: 'Not found',
    clear: 'Clear',
    qty: (n) => `${n}`,
  },

  auth: {
    appName: 'Stow',
    tagline: 'Find anything in your home',
    google: 'Continue with Google',
    or: 'or',
    emailPlaceholder: 'Email address',
    magicLink: 'Email me a link',
    emailCta: 'Continue with email',
    password: 'Password',
    passwordNew: 'Password (8+ characters)',
    signIn: 'Sign in',
    signUp: 'Create account',
    toSignUp: "Don't have an account?  Sign up",
    toSignIn: 'Already have an account?  Sign in',
    orMagic: 'Email me a link instead',
    confirmTitle: 'Check your inbox',
    confirmBody: (email) => `We sent a confirmation link to ${email}.\nTap it to finish signing up.`,
    badCredentials: "That email and password don't match.",
    notConfirmed: 'Your email is not confirmed yet. Tap the link we sent you.',
    alreadyRegistered: 'That email is already registered. Try signing in.',
    passwordTooShort: 'Password must be at least 8 characters.',
    tooMany: 'Too many attempts. Please try again shortly.',
    signInFailed: "Couldn't sign in",
    signUpFailed: "Couldn't create the account",
    sentTitle: 'Check your inbox',
    sentBody: (email) => `Tap the link we sent to ${email} to sign in.`,
    resend: 'Use a different address',
    googleFailed: "Couldn't sign in with Google",
    emailInvalid: 'Check your email',
    emailInvalidBody: 'Please enter a valid email address.',
    sendFailed: "Couldn't send the email",
    signingIn: 'Signing in…',
    linkFailed:
      "That link won't sign you in. It may have expired, been used already, or been requested on another device.",
    linkFailedHint: 'Request a new link from this device.',
  },

  onboarding: {
    chooseTitle: "Let's get started",
    chooseSub: 'Create a household, or join one with an invite code.',
    createCta: 'Create a household',
    joinCta: 'Join with an invite code',
    nameTitle: 'Household name',
    nameSub: 'You can change this later.',
    namePlaceholder: 'Our home',
    nameDefault: 'Our home',
    create: 'Create',
    createFailed: "Couldn't create the household",
    codeTitle: 'Invite code',
    codeSub: 'Enter the 8-character code your family sent you.',
    join: 'Join',
    joinFailed: "Couldn't join",
    joinFailedBody: 'Please check the code and try again.',
  },

  tabs: { find: 'Find', places: 'Places', shopping: 'To buy', more: 'More' },

  find: {
    searchPlaceholder: 'Item name',
    total: (n) => `${n} item${n === 1 ? '' : 's'}`,
    hits: (n) => `${n} found`,
    sortShuffle: 'Shuffled',
    sortRecent: 'Newest first',
    syncing: 'Syncing…',
    offline: (when) => `Offline — last synced ${when}`,
    noItems: 'No items yet',
    noItemsHint: 'Tap + at the bottom right to add your first item.',
    noHits: (q) => `No results for "${q}"`,
    noHitsHint: 'Try part of the name instead.',
    allPlaces: 'All',
    addItem: 'Add item',
    emptyPlace: 'Nothing in this place yet',
    emptyPlaceHint: 'Pick another place, or add an item with the + button.',
    more: (n) => `${n} more`,
  },

  mission: {
    title: "Today's mission",
    hint: (left) => `Add ${left} more item${left === 1 ? '' : 's'}`,
    success: 'Mission complete!',
    successHint: 'Five for today. See you tomorrow.',
    hide: 'Hide for today',
  },

  places: {
    title: 'Home Store',
    section: (n) => `Places${n > 0 ? ` · ${n}` : ''}`,
    addLocation: '+ Place',
    addFailed: "Couldn't add place",
    none: 'No places yet',
    noneHint: 'Start with where you keep things.\nNames like "Hall pantry" or "Balcony storage" work well.',
    boxes: (n) => `${n} box${n === 1 ? '' : 'es'}`,
    summary: (boxes, items) =>
      [boxes > 0 ? `${boxes} box${boxes === 1 ? '' : 'es'}` : null, items > 0 ? `${items} item${items === 1 ? '' : 's'}` : null]
        .filter(Boolean)
        .join(' · ') || 'Empty',
    looseOnly: 'Items, no boxes',
    itemCount: (n) => `${n} item${n === 1 ? '' : 's'}`,
  },

  location: {
    settings: 'Place settings',
    name: 'Place name',
    namePlaceholder: 'e.g. Hall pantry, Balcony storage',
    note: 'Note',
    notePlaceholder: 'Anything to remember about this place',
    nameRequired: 'Name cannot be empty.',
    deleteLocation: 'Delete this place',
    deleteFailed: "Couldn't delete",
    deleteLocationTitle: 'Delete this place?',
    deleteLocationBody: 'It has to be empty first.',
    deleteLocationBlocked: "Can't delete this place",
    addLooseItem: 'Add an item here, without a box',
    boxSection: (n) => `Boxes${n > 0 ? ` · ${n}` : ''}`,
    addBox: '+ Box',
    boxPlaceholder: 'e.g. Box 1, Winter bin',
    boxAddHint: 'Press enter to keep adding.',
    boxAddFailed: "Couldn't add box",
    noBoxes: 'No boxes',
    noBoxesHint: 'Each box gets a QR code automatically.\nItems can also sit here without a box.',
    looseSection: (n) => `Here without a box · ${n}`,
    rename: 'Edit name',
    itemsInside: (n) => `Holds ${n} item${n === 1 ? '' : 's'}.`,
    isEmpty: 'Empty.',
    deleteBoxTitle: 'Delete this box?',
    deleteBoxWithItems: (n, loc) =>
      `The ${n} item${n === 1 ? '' : 's'} inside stay in "${loc}".`,
    deleteBoxEmpty: 'You can restore it from the trash.',
  },

  container: {
    fallbackTitle: 'Box',
    settings: 'Box settings',
    name: 'Box name',
    namePlaceholder: 'e.g. Box 3, Winter bedding',
    label: 'Box label',
    labelHint: 'Cut it out and stick it on — scanning shows what is inside.',
    printLabel: 'Print this label',
    printing: 'Preparing…',
    printFailed: "Couldn't print",
    addItem: 'Add an item to this box',
    contents: (n) => `Contents${n > 0 ? ` · ${n}` : ''}`,
    deleteBox: 'Delete this box',
    deleteTitle: 'Delete this box?',
    deleteWithItems: (n, loc) => `The ${n} item${n === 1 ? '' : 's'} inside stay in "${loc}".`,
    deleteEmpty: 'This box is empty.',
    deleteFailed: "Couldn't delete",
  },

  item: {
    fallbackTitle: 'Item',
    gone: 'Item not found',
    goneHint: 'It was deleted, or you do not have access.',
    location: 'Location',
    loose: ' · no box',
    move: 'Move',
    moving: 'Moving…',
    moveFailed: "Couldn't move it",
    moveTitle: 'Move it where?',
    movedTo: (path: string) => `Moved to ${path}.`,
    addBoxHere: '+ New box here',
    noBoxesYet: 'No boxes',
    addBoxHint: 'The item goes straight into it.',
    moveHere: 'Here now',
    moveToLocation: 'Keep it here, without a box',
    noPlaces: 'No places',
    noPlacesHint: 'Create a place first.',
    addPhoto: '+ Add photo',
    quantity: 'Quantity',
    zeroHint: 'Out of stock — it is on the To-buy list',
    category: 'Category',
    categoryPlaceholder: 'e.g. Household',
    purchaseUrl: 'Where to buy',
    note: 'Note',
    notePlaceholder: 'Anything to remember',
    name: 'Name',
    namePlaceholder: 'Item name',
    nameRequired: 'Name cannot be empty.',
    quantityInvalid: 'Quantity must be a number, 0 or more.',
    qtyFailed: "Couldn't change the quantity",
    saved: 'Saved',
    savedFailed: "Couldn't save",
    history: 'History',
    editedBy: (who, when) => `Edited by ${who} · ${when}`,
    createdAt: (when) => `Added ${when}`,
    formerMember: 'Former member',
    deleteItem: 'Delete this item',
    createdTitle: 'All set!',
    createdWhere: (path) => `Stored in "${path}".`,
    createdOk: 'Nice',
    addMoreHere: (path) => `Add another item to "${path}"`,
    deleteTitle: 'Delete this item?',
    deleteBody: (name) => `"${name}" will be deleted.`,
    deleteFailed: "Couldn't delete",
    saveFailed: "Couldn't save",
    openBox: 'Open this box',
    openLocation: 'Open this place',
  },

  add: {
    namePlaceholder: 'Item name',
    register: 'Add',
    registering: 'Adding…',
    noBox: ' · no box',
    saveFailed: "Couldn't save",
    queueFull: 'Check your connection',
    queueFullBody: (n) =>
      `${n} item${n === 1 ? '' : 's'} are not on the server yet. They will save once you are back online.`,
    pendingSync: (n) => `${n} waiting to sync`,
    cameraPermission: 'Camera permission needed',
  },

  addFlow: {
    step1Title: 'Take a photo',
    step2Title: 'Item details',
    skipPhoto: 'No photo',
    fromGallery: 'Gallery',
    retake: 'Retake',
    noPhoto: 'No photo',
    whereTitle: 'Where does it go?',
    wherePick: 'Change',
    whereNotSet: 'Not chosen yet',
    whereRequired: 'Choose where it goes.',
  },
  camera: {
    zoomNone: 'No zoom',
    zoomLevel: (pct) => `Zoom ${pct}%`,
    preparing: 'Starting camera…',
    restart: 'Restart camera',
    captureFailed: "Couldn't take the photo",
    captureFailedBody: 'Restarting the camera — try again in a moment.',
    photo: 'Photo',
    useThisPhoto: 'Use this photo',
    uploading: 'Uploading…',
    retake: 'Retake',
    replaceHint: 'A new photo replaces the current one.',
    firstHint: 'Tap the shutter to add a photo.',
    removePhoto: 'Remove photo',
    permissionNeeded: 'Camera permission needed',
    permissionBody: 'The camera is used to read the QR labels on your boxes.',
    grantPermission: 'Allow camera',
    photoSaveFailed: "Couldn't save the photo",
    photoRemoveFailed: "Couldn't remove the photo",
  },

  scan: {
    guide: 'Line up the QR label inside the square',
    notOurs: 'Not a Home Store QR code',
    damaged: 'This QR code looks damaged',
    findingBox: 'Finding the box',
    opening: 'Opening',
    scanAgain: 'Scan again',
    unreadable: "Couldn't read the QR code",
    foreignHint: 'It looks like a QR code from another app or site.',
    damagedHint: 'The label may be damaged. Print it again from the box screen.',
    loadFailed: "Couldn't load the box",
    loadFailedHint: 'Check your connection and try again.',
    unregistered: 'No box for this code',
    unregisteredHint: 'Nothing is linked to this QR code.\nIt may belong to another household, or the box was deleted.',
  },

  labels: {
    title: 'Print labels',
    intro: 'Up to 21 labels per A4 sheet. Cut them out and stick them on — scanning shows what is inside.',
    selectAll: 'Select all',
    clear: 'Clear',
    boxCount: (n) => `${n} box${n === 1 ? '' : 'es'}`,
    noBoxes: 'No boxes',
    noBoxesHint: 'Create a box in a place first.',
    pickSome: 'Pick the boxes to print',
    tally: (n, pages, left) =>
      `${n} selected · ${pages} A4 page${pages === 1 ? '' : 's'}` +
      (left > 0 ? ` · ${left} slot${left === 1 ? '' : 's'} left on the last page` : ' · exact fit'),
    print: 'Print',
    making: 'Preparing…',
    sharePdf: 'Save or share as PDF',
    madePdf: 'PDF created',
    failed: "Couldn't create the labels",
  },

  shopping: {
    title: 'To buy',
    none: 'Nothing to buy',
    noneHint: 'When an item runs down to zero,\nit shows up here automatically.',
    section: (n) => `Out of stock · ${n}`,
    remaining: (q) => `${q} left`,
    outOfStock: 'Out of stock',
    buy: 'Buy',
    noLink: 'No link yet — add one when editing the item and it opens from here',
    footNote: 'After you restock, open the item and raise the quantity — it leaves this list.',
    linkFailed: "Couldn't open the link",
  },

  more: {
    title: 'More',
    profile: 'You',
    household: 'Household',
    role: (r) => (r === 'owner' ? 'Owner' : 'Member'),
    memberSince: (when) => `Since ${when}`,
    theme: 'Appearance',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    language: 'Language',
    langSystem: 'System',
    langKo: '한국어',
    langEn: 'English',
    langHint: 'System follows your device language.',
    boxLabels: 'Box labels',
    printLabels: 'Print box labels',
    printHint: 'Up to 21 per A4 sheet. Cut them out and stick them on — scanning shows what is inside.',
    family: 'Household',
    familyValue: (n) => (n === 1 ? '1 person' : `${n} people`),
    trash: 'Trash',
    trashHint: 'Restore deleted items, boxes and places within 30 days.',
    account: 'Account',
    signOut: 'Sign out',
  },

  family: {
    title: 'Household',
    houseName: 'Household name',
    renameFailed: "Couldn't rename",
    members: 'Members',
    memberCount: (n) => (n === 1 ? '1 person' : `${n} people`),
    me: 'You',
    joined: (when) => `Joined ${when}`,
    promote: 'Make owner',
    demote: 'Remove owner role',
    promoteTitle: (name) => `Make ${name} an owner?`,
    promoteBody: 'Owners can invite people and remove members.',
    demoteTitle: (name) => `Remove owner role from ${name}?`,
    demoteBody: 'They will no longer be able to invite or remove people.',
    roleFailed: "Couldn't change the role",
    remove: 'Remove',
    removeTitle: (name) => `Remove ${name}?`,
    removeBody: 'They will lose access to this household. Everything they added stays.',
    removeFailed: "Couldn't remove them",
    invite: 'Invite code',
    inviteHint: 'Give this code to your family and they can join. It never expires.',
    inviteCopy: 'Copy code',
    inviteCopied: 'Copied',
    rotate: 'Change code',
    rotateTitle: 'Switch to a new code?',
    rotateConfirm: 'Change it',
    rotateBody: 'Every code you have shared so far stops working. Anyone who has not joined yet needs the new one.',
    rotateFailed: "Couldn't change the code",
    afterRemoveTitle: 'Change the code too?',
    afterRemoveBody: (name) =>
      `If ${name} knows the invite code they can rejoin with it. Changing the code now prevents that.`,
    afterRemoveKeep: 'Leave it',
    leave: 'Leave this household',
    leaveTitle: (house) => `Leave "${house}"?`,
    leaveBody: 'You will lose access to this household. You need a new invite code to come back.',
    leaveBlocked: 'The last owner cannot leave',
    leaveBlockedHint: 'Make someone else an owner first.',
    leaveFailed: "Couldn't leave",
  },

  deleteAccount: {
    title: 'Delete account',
    confirmTitle: 'Delete your account?',
    summaryDoomed: (n) =>
      `${n} household${n === 1 ? '' : 's'} only you use will be erased, along with every item and photo.`,
    summaryLeaving: (n) =>
      `You will simply leave ${n} household${n === 1 ? '' : 's'} you share. Their items stay.`,
    summaryHandover: 'Households you own are handed over to another family member.',
    irreversible: 'This cannot be undone.',
    confirm: 'Delete',
    failed: "Couldn't delete your account",
    checking: 'Checking…',
    working: 'Deleting…',
  },

  about: {
    section: 'About',
    version: 'Version',
    copyDiagnostics: 'Diagnostics copied',
    updateEmbedded: 'Built-in bundle',
    updateApplied: (when) => `Updated ${when}`,
  },

  licenses: {
    title: 'Open source licenses',
    entry: (n) => `${n}`,
    intro: (n) =>
      `This app uses ${n} open source packages. Tap any entry to open its repository.`,
  },

  photo: {
    change: 'Change photo',
    remove: 'Remove photo',
    removeTitle: 'Remove this photo?',
    removeBody: 'This cannot be undone. You would need to take or pick a new one.',
    zoomHint: 'Pinch to zoom · double-tap to reset',
  },

  /** First-run guidance (2026-09-01) */
  starter: {
    title: 'Get started',
    progress: (done: number, total: number) => `${done}/${total}`,
    step1: 'Create a storage place',
    step1Hint: 'A room, a closet, the garage',
    step2: 'Add your first item',
    step2Hint: 'Snap a photo, give it a name',
    step3: 'Find it by searching',
    step3Hint: 'Partial names work too',
    step4: 'Create a category',
    step4Hint: 'Group things like meds, tools, kids’ stuff — easier to find later',
    open: 'Open',
    hide: 'Hide this',
    doneTitle: "You're all set",
    doneHint: 'Now fill it with what you actually own.',
    finish: "Let's go",
  },

  locSheet: {
    title: 'Create a storage place',
    suggestHint: 'Suggested',
    suggestions: ['Bedroom', 'Kitchen', 'Living room', 'Garage', 'Bathroom', 'Entryway', 'Closet', 'Attic', 'Basement', 'Fridge'],
    manualHint: 'Or type your own',
    placeholder: 'Place name',
    stage: 'Add to list',
    picked: (n) => `Typed · ${n}`,
    alreadyExists: (name) => `${name} already exists.`,
    done: 'Done',
    saveN: (n) => `Add ${n}`,
    saving: 'Adding…',
    addFailed: (names) => `Couldn't add: ${names}`,
    discardTitle: 'Discard your list?',
    discardBody: (n) => `${n} unsaved place(s) will be lost.`,
    discard: 'Discard',
  },

  history: {
    title: 'History',
    none: 'No history yet',
    noneHint: 'Changes to the name, quantity, or location show up here.',
    created: 'Added',
    updated: 'Edited',
    moved: 'Moved',
    qty_changed: 'Quantity changed',
    deleted: 'Deleted',
    restored: 'Restored',
    by: (who) => `${who}`,
  },
  trash: {
    title: 'Trash',
    section: (n) => `Deleted · ${n}`,
    none: 'Trash is empty',
    noneHint: 'Deleted things stay here for 30 days.',
    hint: 'Deleted things disappear for good after 30 days.',
    restore: 'Restore',
    restoring: 'Restoring…',
    kindItem: 'Item',
    kindContainer: 'Box',
    kindLocation: 'Place',
    deletedAt: (when) => `Deleted ${when}`,
    restoreFailed: "Couldn't restore",
    boxRestoreNote: 'Restoring a box does not pull its items back in — they stayed in the place. Add them again.',
  },
  category: {
    title: 'Categories',
    manage: 'Manage categories',
    section: (n) => `Categories · ${n}`,
    manageHint: 'Create and organize the categories you sort items into.',
    add: 'Add category',
    namePlaceholder: 'e.g. Travel, Cosmetics, Party',
    none: 'No categories yet',
    noneHint: 'Create names to group items by,\nlike "Travel" or "Cosmetics".',
    itemCount: (n) => (n > 0 ? `${n} item${n === 1 ? '' : 's'} linked` : 'No items linked'),
    duplicate: 'That name already exists',
    addFailed: "Couldn't create the category",
    renameFailed: "Couldn't rename it",
    deleteFailed: "Couldn't delete it",
    deleteTitle: (name) => `Delete '${name}'?`,
    deleteBodyUsed: (n) =>
      `${n} item${n === 1 ? '' : 's'} linked.\nThe items stay — only their category is cleared.`,
    pickTitle: 'Choose a category',
    pickNone: 'No category',
    empty: 'None',
    goManage: 'Create a category first',
    searchPlaceholder: 'Search categories',
    countAll: (n) => `${n} categories`,
    reorder: 'Reorder',
    reorderDone: 'Done',
    moveUp: 'Move up',
    moveDown: 'Move down',
    edit: 'Edit',
    noMatch: (q) => `No category matches "${q}"`,
    newTitle: 'New category',
    editTitle: 'Edit category',
    nameLabel: 'Name',
    descLabel: 'Description',
    descPlaceholder: 'e.g. Screwdriver, hammer, wrench',
    colorLabel: 'Color',
    iconLabel: 'Icon',
    saveFailed: "Couldn't save",
    tipTitle: 'Tip',
    tipBody: 'Add categories or change their order\nto keep your things easier to find.',
    tipClose: 'Dismiss tip',

  },
  time: {
    justNow: 'just now',
    minutesAgo: (n) => `${n} min ago`,
    hoursAgo: (n) => `${n} hr ago`,
    daysAgo: (n) => `${n} day${n === 1 ? '' : 's'} ago`,
    date: (y, m, d) => `${m}/${d}/${y}`,
    monthDay: (m, d) => `${m}/${d}`,
    noRecord: 'no record',
  },
};
